resolver: nightly-2018-05-06

packages:
  - linear
  - logic
  - location:
      git: https://github.com/LeanderK/numhask.git
      commit: ddb92ec0f1419d8b1058ae4637523320f7a6871a
      subdirs:
        - numhask
    extra-dep: true

extra-deps:
  # - dimensions-0.3.2.0
  # - perf-0.4.1.0
  # - perf-analysis-0.0.1.1
