name:                backbone-logic
version:             0.1.0.0
github:              "hs-backbone/logic"
license:             BSD3
author:              "Leander Kurscheidt"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hs-backbone/logic#readme>

dependencies:
- base >=4.7 && <4.12
- singletons
- numhask >= 0.2.3.0
- ghc-prim
- constraints
- template-haskell
- QuickCheck
- MonadRandom
- array

library:
  source-dirs: src

tests:
  backbone-logic-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backbone-linear
